### ISSUE TITLE
OSS 什么时候引入进来？

### ISSUE THREAD

**Issue by byan** [aliyun/openapi-sdk-php#106]
**您的功能请求是否与问题有关？ 请描述一下。**
请描述您要解决的问题。
OSS 似乎一直独立于 SDK 之外。什么时候可以集成进来？

**描述你想要的解决方案**
请描述所需的行为。
集成 OSS

**描述您考虑过的替代方案**
请描述您考虑的替代解决方案或功能。

**Comment by JacksonTian** [comment]
OSS 因为是不同的 API 风格，所以需要另行维护。暂时没有更好的办法来解决这个问题。

我们有一个新的解决方案，但还未成熟。
