### ISSUE TITLE
就没有针对指定产品单独的sdk吗?

### ISSUE THREAD

**Issue by woann** [aliyun/openapi-sdk-php#109]
比如我只想用一个"移动推送",然而我得把这么大个sdk全down下来??

**Comment by songshenzong** [comment]
> 比如我只想用一个"移动推送",然而我得把这么大个sdk全down下来??

您好，暂时没有，请问您是使用 Composer 安装的吗？

**Comment by larryli** [comment]
#114

**Comment by songshenzong** [comment]
> 比如我只想用一个"移动推送",然而我得把这么大个sdk全down下来??

感谢关注，应您和其他一些客户的要求，我们已经编写、上线了同步分割服务，将完整的SDK依赖包按照产品同步分割到不同的Github仓库，并在Packagist上建立不同的Composer依赖包，我们还同步了版本，这样，您可以随时在SDK和具体产品的依赖包之间自由切换。具体产品的依赖包将在SDK发布后的30分钟内完成分割和发布。已支持产品列表增加了具体产品链接：https://github.com/aliyun/openapi-sdk-php/blob/master/SUPPORTED.md

**Comment by songshenzong** [comment]
> #114

> 比如我只想用一个"移动推送",然而我得把这么大个sdk全down下来??

感谢关注，应您和其他一些客户的要求，我们已经编写、上线了同步分割服务，将完整的SDK依赖包按照产品同步分割到不同的Github仓库，并在Packagist上建立不同的Composer依赖包，我们还同步了版本，这样，您可以随时在SDK和具体产品的依赖包之间自由切换。具体产品的依赖包将在SDK发布后的30分钟内完成分割和发布。已支持产品列表增加了具体产品链接：https://github.com/aliyun/openapi-sdk-php/blob/master/SUPPORTED.md
