### ISSUE TITLE
KMS

### ISSUE THREAD

**Issue by randy86** [aliyun/openapi-sdk-php#12]
where is KMS sdk in this source ? this is available and how to used it ?

**Comment by songshenzong** [comment]
> where is KMS sdk in this source ? this is available and how to used it ?

Hello, this product is temporarily not generated automatically, we are temporarily unavailable, will be provided in the next version.

**Comment by songshenzong** [comment]
> where is KMS sdk in this source ? this is available and how to used it ?

Hello, we have released the KMS SDK, please visit: https://github.com/aliyun/php-kms-sdk
