### ISSUE TITLE
NLS接口报错

### ISSUE THREAD

**Issue by phpha** [aliyun/openapi-sdk-php#126]
* **PHP 版本**：7.1
* **平台**：CentOS
* **产品名称**：
* **产品版本**：
* **API**：

```php
        try {
            //
            $result = AlibabaCloud::nlsFiletrans()->v20180817()
                ->submitTask()
                ->withTask($param)
                ->request();
            // 提交成功
            if (trim($result['StatusText']) == 'SUCCESS') {
                // 返回
                return Helper::returnError(0, [
                    'task_id' => trim($result['TaskId'])
                ]);
            }
        } catch (ClientException $e) {
            // 客户端异常
            return Helper::returnError(1000, [], $e->getErrorMessage());
        } catch (ServerException $e) {
            // 服务端异常
            return Helper::returnError(1000, [], $e->getErrorMessage());
        }
```
报错：
```
Client 'default' not found
```

**Comment by songshenzong** [comment]
> * **PHP 版本**：7.1
> * **平台**：CentOS
> * **产品名称**：
> * **产品版本**：
> * **API**：
> 
> ```
>         try {
>             //
>             $result = AlibabaCloud::nlsFiletrans()->v20180817()
>                 ->submitTask()
>                 ->withTask($param)
>                 ->request();
>             // 提交成功
>             if (trim($result['StatusText']) == 'SUCCESS') {
>                 // 返回
>                 return Helper::returnError(0, [
>                     'task_id' => trim($result['TaskId'])
>                 ]);
>             }
>         } catch (ClientException $e) {
>             // 客户端异常
>             return Helper::returnError(1000, [], $e->getErrorMessage());
>         } catch (ServerException $e) {
>             // 服务端异常
>             return Helper::returnError(1000, [], $e->getErrorMessage());
>         }
> ```
> 
> 报错：
> 
> ```
> Client 'default' not found
> ```

请在使用前，设置客户端。 https://github.com/aliyun/openapi-sdk-php-client/blob/master/docs/zh/2-Client.md

**Comment by phpha** [comment]
thks
