### ISSUE TITLE
composer failed

### ISSUE THREAD

**Issue by bbdlg** [aliyun/openapi-sdk-php#133]
各种Reading和Downloading之后...

Reading /Users/sarry/.composer/cache/repo/https---packagist.phpcomposer.com/provider-phpunit$phpunit-mock-objects.json from cache
Downloading https://repo.packagist.org/p/phpunit/phpunit-mock-objects.json
Resolving dependencies through SAT

Dependency resolution completed in 0.013 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install alibabacloud/client 1.5.9
    - Conclusion: don't install alibabacloud/client 1.5.8
    - Conclusion: don't install alibabacloud/client 1.5.7
    - Conclusion: don't install alibabacloud/client 1.5.6
    - Conclusion: don't install alibabacloud/client 1.5.5
    - Conclusion: don't install alibabacloud/client 1.5.4
    - Conclusion: don't install alibabacloud/client 1.5.3
    - Conclusion: don't install alibabacloud/client 1.5.2
    - Installation request for alibabacloud/client (locked at 1.0.23, required as ^1.0) -> satisfiable by alibabacloud/client[1.0.23].
    - Conclusion: don't install alibabacloud/client 1.5.1
    - alibabacloud/sdk 1.7.0 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
    - alibabacloud/sdk 1.7.1 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
    - alibabacloud/sdk 1.7.2 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
    - alibabacloud/sdk 1.7.3 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
    - alibabacloud/sdk 1.7.4 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
    - alibabacloud/sdk 1.7.5 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
    - alibabacloud/sdk 1.7.6 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
    - alibabacloud/sdk 1.7.7 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
    - alibabacloud/sdk 1.7.8 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
    - alibabacloud/sdk 1.7.9 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
    - Conclusion: don't install alibabacloud/client 1.5.0
    - Installation request for alibabacloud/sdk ^1.7 -> satisfiable by alibabacloud/sdk[1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9].

Installation failed, reverting ./composer.json to its original content.

**Comment by songshenzong** [comment]
> 各种Reading和Downloading之后...
> 
> Reading /Users/sarry/.composer/cache/repo/https---packagist.phpcomposer.com/provider-phpunit$phpunit-mock-objects.json from cache
> Downloading https://repo.packagist.org/p/phpunit/phpunit-mock-objects.json
> Resolving dependencies through SAT
> 
> Dependency resolution completed in 0.013 seconds
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - Conclusion: don't install alibabacloud/client 1.5.9
> - Conclusion: don't install alibabacloud/client 1.5.8
> - Conclusion: don't install alibabacloud/client 1.5.7
> - Conclusion: don't install alibabacloud/client 1.5.6
> - Conclusion: don't install alibabacloud/client 1.5.5
> - Conclusion: don't install alibabacloud/client 1.5.4
> - Conclusion: don't install alibabacloud/client 1.5.3
> - Conclusion: don't install alibabacloud/client 1.5.2
> - Installation request for alibabacloud/client (locked at 1.0.23, required as ^1.0) -> satisfiable by alibabacloud/client[1.0.23].
> - Conclusion: don't install alibabacloud/client 1.5.1
> - alibabacloud/sdk 1.7.0 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
> - alibabacloud/sdk 1.7.1 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
> - alibabacloud/sdk 1.7.2 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
> - alibabacloud/sdk 1.7.3 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
> - alibabacloud/sdk 1.7.4 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
> - alibabacloud/sdk 1.7.5 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
> - alibabacloud/sdk 1.7.6 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
> - alibabacloud/sdk 1.7.7 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
> - alibabacloud/sdk 1.7.8 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
> - alibabacloud/sdk 1.7.9 requires alibabacloud/client ^1.5 -> satisfiable by alibabacloud/client[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9].
> - Conclusion: don't install alibabacloud/client 1.5.0
> - Installation request for alibabacloud/sdk ^1.7 -> satisfiable by alibabacloud/sdk[1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9].
> 
> Installation failed, reverting ./composer.json to its original content.

因为 SDK 依赖 Client，请删除已经安装的可能是旧版本的 Client 再尝试。
