### ISSUE TITLE
无法获取容器镜像服务仓库列表

### ISSUE THREAD

**Issue by Veitor** [aliyun/openapi-sdk-php#143]
* **PHP 版本**：7.2.6
* **平台**：docker alpine
* **产品名称**：容器镜像服务Cr
* **产品版本**：20160607
* **API**：getRepoList

代码基本是拿官网文档过来后做的修改：
```php
AlibabaCloud::accessKeyClient('xxx','xxx')->regionId('cn-hangzhou')->asDefaultClient();

try {
	$options = [
	    'debug' => true,
	    'query' => [
	        'Status' => 'NORMAL',
	        'RepoNamePrefix' => ''
	    ]
	];
	$request = Cr::v20160607()
	            ->getRepoList($options);

	$r = $request->request();
} catch (ServerException $e) {
    echo $e->getResult();
}
```

最后捕获打出来的结果是：
```json
{"RequestId":"806D70E8-32B0-4F18-8C8A-CA54E5D22E2E","HostId":"location.aliyuncs.com","Code":"Illegal Parameter","Message":"Please check the parameters"}
```

不清楚是哪里参数有误。
而且API文档https://help.aliyun.com/document_detail/72399.html 上还有个RepoNamePrefix参数，要求是必须提供该参数，但SDK中又没有`AlibabaCloud\Cr\V20160607\GetRepoList::withRepoNamePrefix()`这样的函数，所以我通过options['query']进行了传递，不知道是否正确。

accessKeyId和accessKeySecret都是正确的
到底哪里出现了参数错误？

**Comment by Veitor** [comment]
好的

**Comment by chenjiayao** [comment]
@Veitor  请问这个问题后来是如何解决的，我这边碰到了同款问题

**Comment by yizhihouzi** [comment]
@chenjiayao @Veitor @songshenzong  
问题的原因在于 产品名称 'cr' 与 'acr'的混淆,具体见下面:

文件: vendor/alibabacloud/client/src/Traits/EndpointTrait.php
method: resolveHost
获得cr的服务地址代码:
$domain = Config::get("endpoints.{$product}.{$regionId}");
此处的product值为 'cr'
见:
文件:vendor/alibabacloud/sdk/src/Cr/V20160607/CrApiResolver.php
第80行:
    public $product = 'cr';

而
文件:vendor/alibabacloud/client/src/Config/Data.php
第 2333行配置的名称为 'acr'

望尽快修复.
