### ISSUE TITLE
Exception running 'composer require alibabacloud/iot'

### ISSUE THREAD

**Issue by borrown** [aliyun/openapi-sdk-php#144]
When I run the suggested command (composer require alibabacloud/iot) into the main folder of my project I got the next exception:

 [Composer\Downloader\TransportException]                                                                                                                                      
  The "https://packagist.org/p/provider-2018-10%24f46f061cec1b6a87bfb524e0ffda75e654a332e87c103dbe60e9e0adb50469eb.json" file could not be downloaded (HTTP/1.1 404 Not Found)

**Comment by songshenzong** [comment]
It may be an official temporary error. Please try again.

**Comment by borrown** [comment]
It works now. Thanks for your time.
