### ISSUE TITLE
是否支持媒体处理

### ISSUE THREAD

**Issue by JeffreyBool** [aliyun/openapi-sdk-php#145]
https://help.aliyun.com/document_detail/59877.html?spm=a2c4g.11186623.6.780.2ce445b8Jwe6zM

**Comment by songshenzong** [comment]
> https://help.aliyun.com/document_detail/59877.html?spm=a2c4g.11186623.6.780.2ce445b8Jwe6zM

已支持这个接口，具体用法请参考文档。
