### ISSUE TITLE
composer require alibabacloud/sdk 会删除文件 请谨慎使用

### ISSUE THREAD

**Issue by alexosng** [aliyun/openapi-sdk-php#150]
* **PHP Version**:PHP 7.2
* **Platform**: Mac OS 10.14.6 X64
* **Product**: 
* **Product Version**:
* **API**: composer require alibabacloud/sdk

tp5.05 项目根目录中 
运行： composer require alibabacloud/sdk 安装成功，
结果：thinkphp目录中的 start.php 被无缘无故删除。导致项目不能运行。
测试次数：3次，
测试结果：文件均被删除

**Comment by songshenzong** [comment]
请将回复您本地 composer.json 文件

**Comment by songshenzong** [comment]
> 请将回复您本地 composer.json 文件

如果没有问题，我们将关闭 ISSUE
