### ISSUE TITLE
What's the diference between `retryByClient()` and `retryByServer()`?

### ISSUE THREAD

**Issue by balthild** [aliyun/openapi-sdk-php#151]
According to `vendor/alibabacloud/client/src/Request/Request.php`, a "Server Retry" is calling `request()` again, and a "Client Retry" is calling `response()` again. But `request()` is just `resolveOption()` + `response()`. Also, both `shouldServerRetry()` and `shouldClientRetry()` determines the status code returned from GuzzleHttp. It seems that they behave the same. So which should I use for ensuring the idempotent (https://help.aliyun.com/document_detail/25693.html)?

**Comment by songshenzong** [comment]
> According to `vendor/alibabacloud/client/src/Request/Request.php`, a "Server Retry" is calling `request()` again, and a "Client Retry" is calling `response()` again. But `request()` is just `resolveOption()` + `response()`. Also, both `shouldServerRetry()` and `shouldClientRetry()` determines the status code returned from GuzzleHttp. It seems that they behave the same. So which should I use for ensuring the idempotent (https://help.aliyun.com/document_detail/25693.html)?

You can see: https://github.com/aliyun/openapi-sdk-php-client/blob/master/docs/en-US/3-Request.md#retry

**Comment by balthild** [comment]
The doc does not explain the exact differences between the two methods. What would happen if I use `->retryByClient(3, ['a', 'b'], [500, 502])` over `->retryByServer(3, ['a', 'b'], [500, 502])` ?

**Comment by songshenzong** [comment]
> The doc does not explain the exact differences between the two methods. What would happen if I use `->retryByClient(3, ['a', 'b'], [500, 502])` over `->retryByServer(3, ['a', 'b'], [500, 502])` ?

![image](https://user-images.githubusercontent.com/17404625/63680516-72b09b80-c826-11e9-8d58-117be36b3d43.png)

**Comment by songshenzong** [comment]
If there are no other questions, we will close this issue.
