### ISSUE TITLE
CAS服务API版本与文档比较缺失

### ISSUE THREAD

**Issue by xiaohuilam** [aliyun/openapi-sdk-php#156]
**https://github.com/aliyun/openapi-sdk-php/tree/master/src/Cas**
目前SDK有且只有 V20180813

而文档是   [V20180713](https://help.aliyun.com/document_detail/126507.html) + V20180813

**Comment by songshenzong** [comment]
> **https://github.com/aliyun/openapi-sdk-php/tree/master/src/Cas**
> 目前SDK有且只有 V20180813
> 
> 而文档是 [V20180713](https://help.aliyun.com/document_detail/126507.html) + V20180813

已收到，我们会联系产品方核实、发布。

**Comment by songshenzong** [comment]
> **https://github.com/aliyun/openapi-sdk-php/tree/master/src/Cas**
> 目前SDK有且只有 V20180813
> 
> 而文档是 [V20180713](https://help.aliyun.com/document_detail/126507.html) + V20180813

经和产品方核实，两个版本一样，另一个版本无需发布。

**Comment by xiaohuilam** [comment]
> > **https://github.com/aliyun/openapi-sdk-php/tree/master/src/Cas**
> > 目前SDK有且只有 V20180813
> > 而文档是 [V20180713](https://help.aliyun.com/document_detail/126507.html) + V20180813
> 
> 经和产品方核实，两个版本一样，另一个版本无需发布。

经测试20180813的sdk已封装api缺少20180713版本的API

**Comment by zhanglihai** [comment]
> **https://github.com/aliyun/openapi-sdk-php/tree/master/src/Cas**
> 目前SDK有且只有 V20180813
> 
> 而文档是 [V20180713](https://help.aliyun.com/document_detail/126507.html) + V20180813

你需要使用哪些功能？

**Comment by xiaohuilam** [comment]
> > **https://github.com/aliyun/openapi-sdk-php/tree/master/src/Cas**
> > 目前SDK有且只有 V20180813
> > 而文档是 [V20180713](https://help.aliyun.com/document_detail/126507.html) + V20180813
> 
> 你需要使用哪些功能？

https://help.aliyun.com/document_detail/126507.html

**Comment by zhanglihai** [comment]
> > > **https://github.com/aliyun/openapi-sdk-php/tree/master/src/Cas**
> > > 目前SDK有且只有 V20180813
> > > 而文档是 [V20180713](https://help.aliyun.com/document_detail/126507.html) + V20180813
> > 
> > 
> > 你需要使用哪些功能？
> 
> https://help.aliyun.com/document_detail/126507.html

目前这个功能，只能从 V20180713  版本中获取，并且只有Java版本的。你可以用吗？

**Comment by xiaohuilam** [comment]
> > > > **https://github.com/aliyun/openapi-sdk-php/tree/master/src/Cas**
> > > > 目前SDK有且只有 V20180813
> > > > 而文档是 [V20180713](https://help.aliyun.com/document_detail/126507.html) + V20180813
> > > 
> > > 
> > > 你需要使用哪些功能？
> > 
> > 
> > https://help.aliyun.com/document_detail/126507.html
> 
> 目前这个功能，只能从 V20180713 版本中获取，并且只有Java版本的。你可以用吗？

我项目是PHP的
另外我在PHPsdk里面 vendor下自己去加了版本类调用成功了的

**Comment by songshenzong** [comment]
> **https://github.com/aliyun/openapi-sdk-php/tree/master/src/Cas**
> 目前SDK有且只有 V20180813
> 
> 而文档是 [V20180713](https://help.aliyun.com/document_detail/126507.html) + V20180813

产品已发布，此 Issue 将被关闭。

**Comment by xiaohuilam** [comment]
Thanks a lot, bro
