### ISSUE TITLE
阿里工程师们不考虑开发者的体验么

### ISSUE THREAD

**Issue by huangdengpan** [aliyun/openapi-sdk-php#158]

**Comment by songshenzong** [comment]
> 其实我就想知道这个包怎么用，很多应用场景，是没有权限去装这些包的。那现在就是直接拒绝开发者了。
> 好奇其他大佬都是怎么用这个包的？

可以使用 composer 安装或者下载zip引入

**Comment by huangdengpan** [comment]
> > 其实我就想知道这个包怎么用，很多应用场景，是没有权限去装这些包的。那现在就是直接拒绝开发者了。
> > 好奇其他大佬都是怎么用这个包的？
> 
> 可以使用 composer 安装或者下载zip引入

哎呀，竟然被回复了。主要是一些人没用过composer或者说需要include一个文件，而没提示要include哪个文件。。。。希望再完善下。毕竟文档还是要考虑到大众（小白也是人啊）
