### ISSUE TITLE
找不到vod的方法

### ISSUE THREAD

**Issue by sdgvdvsdf** [aliyun/openapi-sdk-php#159]
安装：
![image](https://user-images.githubusercontent.com/28881955/78129148-b49f6100-7449-11ea-81b6-49729885df6a.png)
使用：
![image](https://user-images.githubusercontent.com/28881955/78129237-d4cf2000-7449-11ea-8be0-c33efc0aef1e.png)
寻找此类与方法：
![image](https://user-images.githubusercontent.com/28881955/78129433-2d062200-744a-11ea-9d7d-6e402bc9abd4.png)

**Comment by songshenzong** [comment]
> 安装：
> ![image](https://user-images.githubusercontent.com/28881955/78129148-b49f6100-7449-11ea-81b6-49729885df6a.png)
> 使用：
> ![image](https://user-images.githubusercontent.com/28881955/78129237-d4cf2000-7449-11ea-8be0-c33efc0aef1e.png)
> 寻找此类与方法：
> ![image](https://user-images.githubusercontent.com/28881955/78129433-2d062200-744a-11ea-9d7d-6e402bc9abd4.png)



> 安装：
> ![image](https://user-images.githubusercontent.com/28881955/78129148-b49f6100-7449-11ea-81b6-49729885df6a.png)
> 使用：
> ![image](https://user-images.githubusercontent.com/28881955/78129237-d4cf2000-7449-11ea-8be0-c33efc0aef1e.png)
> 寻找此类与方法：
> ![image](https://user-images.githubusercontent.com/28881955/78129433-2d062200-744a-11ea-9d7d-6e402bc9abd4.png)

文档中是旧版本的demo，新版请参考ecs用法：
![image](https://user-images.githubusercontent.com/17404625/78148746-cb54b080-7467-11ea-8e87-9bd7ad8590d9.png)

**Comment by sdgvdvsdf** [comment]
好吧，谢谢了。麻烦你们开发与文档同步好吗？这样半吊子叫客户怎么用？还有类库也要适当做swoole兼容了，过多的静态。谢谢！

**Comment by songshenzong** [comment]
> 好吧，谢谢了。麻烦你们开发与文档同步好吗？这样半吊子叫客户怎么用？还有类库也要适当做swoole兼容了，过多的静态。谢谢！

好的。

**Comment by songshenzong** [comment]
> 好吧，谢谢了。麻烦你们开发与文档同步好吗？这样半吊子叫客户怎么用？还有类库也要适当做swoole兼容了，过多的静态。谢谢！

可否告知您的电子邮箱或其他联系方式？

**Comment by sdgvdvsdf** [comment]
邮箱:2199182260@qq.com------------------ 原始邮件 ------------------
发件人: "宋神宗"<notifications@github.com>
发送时间: 2020年4月2日(星期四) 上午9:23
收件人: "aliyun/openapi-sdk-php"<openapi-sdk-php@noreply.github.com>;
抄送: "sdgvdvsdf"<2199182260@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [aliyun/openapi-sdk-php] 找不到vod的方法 (#159)




  
好吧，谢谢了。麻烦你们开发与文档同步好吗？这样半吊子叫客户怎么用？还有类库也要适当做swoole兼容了，过多的静态。谢谢！
  
可否告知您的电子邮箱或其他联系方式？
 
&mdash;
