### ISSUE TITLE
STS获取accessToken出师不利

### ISSUE THREAD

**Issue by huangdengpan** [aliyun/openapi-sdk-php#160]
提示：May not yet support product Sts quick access, you can use [Alibaba Cloud Client for PHP] to send any custom requests: https://github.com/aliyun/openapi-sdk-php-client/blob/master/docs/en-US/3-Request.md

大佬们求救，第一次用阿里云的这种SDK方式。有点懵。如下图所示，提示错误如上图。

我现在是想WEB上传文件到OSS，目前看文档说是要通过AK的方式来获取令牌环，然后用令牌环来上传文件，就是这个accessToken，卡这一步了。不知道逻辑上对不对，求救。

**Comment by huangdengpan** [comment]
![image](https://user-images.githubusercontent.com/16663404/78281914-029d8d00-754e-11ea-9da5-e324ecc47e13.png)

**Comment by huangdengpan** [comment]
这样竟然也不对，根据官方提示写了好几种模型了都走不通。
![image](https://user-images.githubusercontent.com/16663404/78283071-db47bf80-754f-11ea-9a36-4b4ea882b374.png)

**Comment by huangdengpan** [comment]
Fatal error: Class 'AlibabaCloud\Sts\Sts' not found

**Comment by huangdengpan** [comment]
有没有研发人员给看下，这个文档问过了周边的人，没人看得懂啊。以前的SDK库都比较直观理解，现在这一版本的缺乏实操案例，实在是看不懂。我感觉好像少了很多参数提示。

**Comment by songshenzong** [comment]
> Fatal error: Class 'AlibabaCloud\Sts\Sts' not found

安装这个就好了：composer require alibabacloud/sdk

**Comment by wengxianxun** [comment]
阿里云的sdk真是一言难尽，高薪招这么多技术，写的什么乱七八糟的sdk
