### ISSUE TITLE
请问阿里云 afs的包怎么用？

### ISSUE THREAD

**Issue by alpha2016** [aliyun/openapi-sdk-php#161]
我看就两个文件，然后和官方demo完全不一致在，这个怎么用啊？

顺带今天下午官方demo都是 ic error，这个怎么解决？

**Comment by sdk-team** [comment]
> 我看就两个文件，然后和官方demo完全不一致在，这个怎么用啊？
> 
> 顺带今天下午官方demo都是 ic error，这个怎么解决？

是否已提工单？

**Comment by alpha2016** [comment]
> > 我看就两个文件，然后和官方demo完全不一致在，这个怎么用啊？
> > 顺带今天下午官方demo都是 ic error，这个怎么解决？
> 
> 是否已提工单？

提了，工单也没说怎么用，我看不明白了，大佬怎么指教

**Comment by sdk-team** [comment]
> > > 我看就两个文件，然后和官方demo完全不一致在，这个怎么用啊？
> > > 顺带今天下午官方demo都是 ic error，这个怎么解决？
> > 
> > 
> > 是否已提工单？
> 
> 提了，工单也没说怎么用，我看不明白了，大佬怎么指教

请回复钉钉号，钉钉联系。

**Comment by alpha2016** [comment]
$result = AlibabaCloud::rpc()
                ->regionId('cn-hangzhou')
                ->product('Afs')
                ->action('AuthenticateSig')
                ->format('json')
                ->method('POST')
                ->scheme('https')
                ->version('2018-01-12')
                ->host('afs.aliyuncs.com')
                ->debug(false)
               ->withXXX(xxx)
               ->request();

这样才好了，提工单是roa模式的话，代码一样，然后报错缺少必要参数，rpc 才是正确的
