### ISSUE TITLE
建议各产品拆成独立的sdk？

### ISSUE THREAD

**Issue by mrold** [aliyun/openapi-sdk-php#162]
安装一个sdk，要下载全部，这不科学。还有你们的支付接口的sdk，也是一样的。

**Comment by JacksonTian** [comment]
@mrold 我们提供了单独 SDK 的安装方式。 @songshenzong  需要提升一下 README 和文档，告知 all-in-one 和单独包的两种方式。

**Comment by songshenzong** [comment]
> 安装一个sdk，要下载全部，这不科学。还有你们的支付接口的sdk，也是一样的。

你好，我们除了 All in One 的SDK包，还会自动拆分每个产品发布称独立的包，并且会自动更新文档，https://github.com/aliyun/openapi-sdk-php/blob/master/SUPPORTED.md

**Comment by mrold** [comment]
@JacksonTian @songshenzong  是我唐突了，为你们点赞！
