### ISSUE TITLE
OSS 的SDK 呢？

### ISSUE THREAD

**Issue by cuiqg** [aliyun/openapi-sdk-php#166]
差OSS 的SDK呢

**Comment by songshenzong** [comment]
> 差OSS 的SDK呢

https://packagist.org/packages/aliyuncs/oss-sdk-php

**Comment by cuiqg** [comment]
我的意思是没有打包到 alibabacloud/sdk 里面

**Comment by songshenzong** [comment]
> 我的意思是没有打包到 alibabacloud/sdk 里面

OSS不会打包到整体的SDK里，并且每个产品的SDK都有独立发布，推荐：
https://github.com/aliyun/alibabacloud-oss-sdk
