### ISSUE TITLE
车牌识别需要include什么文件呢？也没有autoload

### ISSUE THREAD

**Issue by duqingnian** [aliyun/openapi-sdk-php#168]
use AlibabaCloud\Client\AlibabaCloud;
use AlibabaCloud\Client\Exception\ClientException;
use AlibabaCloud\Client\Exception\ServerException;

这个你告诉我你的openapi-sdk-php-master里 是什么文件？没头没脑的sdk，看得人恼火不已

**Comment by songshenzong** [comment]
> use AlibabaCloud\Client\AlibabaCloud;
> use AlibabaCloud\Client\Exception\ClientException;
> use AlibabaCloud\Client\Exception\ServerException;
> 
> 这个你告诉我你的openapi-sdk-php-master里 是什么文件？没头没脑的sdk，看得人恼火不已

请问是第三方API还是阿里云的RecognizeLicensePlate接口？

**Comment by songshenzong** [comment]
> use AlibabaCloud\Client\AlibabaCloud;
> use AlibabaCloud\Client\Exception\ClientException;
> use AlibabaCloud\Client\Exception\ServerException;
> 
> 这个你告诉我你的openapi-sdk-php-master里 是什么文件？没头没脑的sdk，看得人恼火不已

如果是OCR的车牌识别，请参考：https://github.com/aliyun/openapi-sdk-php/blob/master/demo/ocr.php
