### ISSUE TITLE
文档在哪里？样例在哪里？

### ISSUE THREAD

**Issue by beimuaihui** [aliyun/openapi-sdk-php#169]
文档在哪里？样例在哪里？这不是基本的嘛，花了几天时间，结果是返回用旧版的。

**Comment by songshenzong** [comment]
> 文档在哪里？样例在哪里？这不是基本的嘛，花了几天时间，结果是返回用旧版的。

请问是要使用哪个产品呢？

**Comment by beimuaihui** [comment]
VOD HLS标准加密 还有播放相关

**Comment by songshenzong** [comment]
> VOD HLS标准加密 还有播放相关



> VOD HLS标准加密 还有播放相关

可根据产品的API文档，参考 https://github.com/aliyun/openapi-sdk-php/blob/master/README-zh-CN.md 请求样例发起请求。
