### ISSUE TITLE
CCS的配置有错？或者CCS的SDK还不完整？

### ISSUE THREAD

**Issue by softwarezhu** [aliyun/openapi-sdk-php#17]
你好，我在CCS的配置文件里面发现是这样配置的：
`'ccs'             =>
                [
                    'cn-hangzhou' => 'ccs.aliyuncs.com',
                ],
`
但是我在官方文档中看到的URL是这样的：https://cschat-ccs.aliyun.com/openapi/forwardMessage?tntInstId=XXX&scene=YYY&src=outerservice&timestamp=1487230487910&digest=ZZZ

域名为什么不对？

另外，官方文档中的forwardMessage、tntInstId在整个SDK中都找不到。

是不是CCS的SDK还不完整？或者是不是我哪里错了？

**Comment by songshenzong** [comment]
> 你好，我在CCS的配置文件里面发现是这样配置的：
> `'ccs' => [ 'cn-hangzhou' => 'ccs.aliyuncs.com', ], `
> 但是我在官方文档中看到的URL是这样的：https://cschat-ccs.aliyun.com/openapi/forwardMessage?tntInstId=XXX&scene=YYY&src=outerservice&timestamp=1487230487910&digest=ZZZ
> 
> 域名为什么不对？
> 
> 另外，官方文档中的forwardMessage、tntInstId在整个SDK中都找不到。
> 
> 是不是CCS的SDK还不完整？或者是不是我哪里错了？

请问您使用的CCS服务是哪一个版本？（version字段）

**Comment by songshenzong** [comment]
> 你好，我在CCS的配置文件里面发现是这样配置的：
> `'ccs' => [ 'cn-hangzhou' => 'ccs.aliyuncs.com', ], `
> 但是我在官方文档中看到的URL是这样的：https://cschat-ccs.aliyun.com/openapi/forwardMessage?tntInstId=XXX&scene=YYY&src=outerservice&timestamp=1487230487910&digest=ZZZ
> 
> 域名为什么不对？
> 
> 另外，官方文档中的forwardMessage、tntInstId在整个SDK中都找不到。
> 
> 是不是CCS的SDK还不完整？或者是不是我哪里错了？

请问这个问题还存在吗？

**Comment by songshenzong** [comment]
> 是V20171001版本的，问题依旧存在

可否提供联系方式进一步沟通？

**Comment by softwarezhu** [comment]
qq: 419128626

**Comment by songshenzong** [comment]
> qq: 419128626

请问您有钉钉号吗？ 我们工作不能使用QQ和微信。
