### ISSUE TITLE
"message": "Class 'AlibabaCloud\\Client\\AlibabaCloud' not found",

### ISSUE THREAD

**Issue by Krunal79-flutter** [aliyun/openapi-sdk-php#171]
"message": "Class 'AlibabaCloud\\Client\\AlibabaCloud' not found", In laravel

**Comment by skys215** [comment]
you must `use AlibabaCloud\Client\AlibabaCloud;`

**Comment by songshenzong** [comment]
> "message": "Class 'AlibabaCloud\Client\AlibabaCloud' not found", In laravel

use AlibabaCloud\Client\AlibabaCloud;
