### ISSUE TITLE
为什么不把日志服务SDK也加进来呢？

### ISSUE THREAD

**Issue by Veitor** [aliyun/openapi-sdk-php#173]
目前看SLS日志服务的SDK是单独的 https://github.com/aliyun/aliyun-log-php-sdk
是否考虑也加进来统一规范管理

**Comment by songshenzong** [comment]
> 目前看SLS日志服务的SDK是单独的 https://github.com/aliyun/aliyun-log-php-sdk
> 是否考虑也加进来统一规范管理

暂无计划支持
