### ISSUE TITLE
阿里云一键取号API报 Specified parameter Version is not valid

### ISSUE THREAD

**Issue by 111Quentin** [aliyun/openapi-sdk-php#175]
我这边因为项目是php5.6,不能用composer方式引入项目，所以只能去研究阿里云一键取号Api的接口参数去请求，
结果其他请求参数都没有问题，参数Version就报错，https://api.aliyun.com/new?spm=a2c4g.11186623.2.13.2fc27861OpQnPn#/?product=Dypnsapi&version=2017-05-25&api=GetMobile&params={%22RegionId%22:%22cn-hangzhou%22}&tab=DEMO&lang=PHP   这个url里面的version是填  2017-05-25，我也是填这个，结果就报错了。 想问下version参数应该怎么填
![image](https://user-images.githubusercontent.com/30485197/88379841-296e2080-cdd6-11ea-836a-7b3063a599b4.png)

**Comment by 111Quentin** [comment]
![image](https://user-images.githubusercontent.com/30485197/88380215-badd9280-cdd6-11ea-9bd9-8e63790751e5.png)

**Comment by 111Quentin** [comment]
string(353) "<?xml version='1.0' encoding='UTF-8'?><Error><RequestId>93ABDCE5-4D1A-4861-B38E-D31BDC709E4B</RequestId><HostId>dypnsapi.aliyuncs.com</HostId><Code>InvalidVersion</Code><Message>Specified parameter Version is not valid.</Message><Recommend><![CDATA[https://error-center.aliyun.com/status/search?Keyword=InvalidVersion&source=PopGw]]></Recommend></Error>"

**Comment by songshenzong** [comment]
> 我这边因为项目是php5.6,不能用composer方式引入项目，所以只能去研究阿里云一键取号Api的接口参数去请求，
> 结果其他请求参数都没有问题，参数Version就报错，[https://api.aliyun.com/new?spm=a2c4g.11186623.2.13.2fc27861OpQnPn#/?product=Dypnsapi&version=2017-05-25&api=GetMobile&params={%22RegionId%22:%22cn-hangzhou%22}&tab=DEMO&lang=PHP](https://api.aliyun.com/new?spm=a2c4g.11186623.2.13.2fc27861OpQnPn#/?product=Dypnsapi&version=2017-05-25&api=GetMobile&params=%7B%22RegionId%22:%22cn-hangzhou%22%7D&tab=DEMO&lang=PHP) 这个url里面的version是填 2017-05-25，我也是填这个，结果就报错了。 想问下version参数应该怎么填
> ![image](https://user-images.githubusercontent.com/30485197/88379841-296e2080-cdd6-11ea-836a-7b3063a599b4.png)

支持版本是：2017-05-25
5.6 支持 Composer 安装，如果无法使用 Composer 安装，请下载引入：https://github.com/aliyun/openapi-sdk-php/blob/master/docs/zh-CN/1-Installation.md

**Comment by 111Quentin** [comment]
就是composer方式可以安装，但是由于里面使用guzzlehttp方式请求接口，guzzlehttp类库是用php7+的语法，导致我这边无法用你们推荐的方式去请求一键取号接口。所以我这边只能去追源码看一键取号接口是怎么请求的，我把参数还有参数的加密都自己封装了一遍去请求，结果报version参数不合法，我version填的是2017-05-25，是没问题的。 但是我使用php7以上版本，用你们推荐的rpc去请求接口就能正常拿到手机号，这里填的version参数也是2017-05-25




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "宋神宗"<notifications@github.com&gt;; 
发送时间: 2020年7月25日(星期六) 晚上6:08
收件人: "aliyun/openapi-sdk-php"<openapi-sdk-php@noreply.github.com&gt;; 
抄送: "1551881447"<1551881447@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [aliyun/openapi-sdk-php] 阿里云一键取号API报 Specified parameter Version is not valid (#175)





  
我这边因为项目是php5.6,不能用composer方式引入项目，所以只能去研究阿里云一键取号Api的接口参数去请求，
 结果其他请求参数都没有问题，参数Version就报错，https://api.aliyun.com/new?spm=a2c4g.11186623.2.13.2fc27861OpQnPn#/?product=Dypnsapi&amp;version=2017-05-25&amp;api=GetMobile&amp;params={%22RegionId%22:%22cn-hangzhou%22}&amp;tab=DEMO&amp;lang=PHP 这个url里面的version是填 2017-05-25，我也是填这个，结果就报错了。 想问下version参数应该怎么填
 
  
支持版本是：2017-05-25
 5.6 支持 Composer 安装，如果无法使用 Composer 安装，请下载引入：https://github.com/aliyun/openapi-sdk-php/blob/master/docs/zh-CN/1-Installation.md

**Comment by songshenzong** [comment]
> 就是composer方式可以安装，但是由于里面使用guzzlehttp方式请求接口，guzzlehttp类库是用php7+的语法，导致我这边无法用你们推荐的方式去请求一键取号接口。所以我这边只能去追源码看一键取号接口是怎么请求的，我把参数还有参数的加密都自己封装了一遍去请求，结果报version参数不合法，我version填的是2017-05-25，是没问题的。 但是我使用php7以上版本，用你们推荐的rpc去请求接口就能正常拿到手机号，这里填的version参数也是2017-05-25
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "宋神宗"<notifications@github.com&gt;; 发送时间: 2020年7月25日(星期六) 晚上6:08 收件人: "aliyun/openapi-sdk-php"<openapi-sdk-php@noreply.github.com&gt;; 抄送: "1551881447"<1551881447@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [aliyun/openapi-sdk-php] 阿里云一键取号API报 Specified parameter Version is not valid (#175) 我这边因为项目是php5.6,不能用composer方式引入项目，所以只能去研究阿里云一键取号Api的接口参数去请求， 结果其他请求参数都没有问题，参数Version就报错，[https://api.aliyun.com/new?spm=a2c4g.11186623.2.13.2fc27861OpQnPn#/?product=Dypnsapi&amp;version=2017-05-25&amp;api=GetMobile&amp;params={%22RegionId%22:%22cn-hangzhou%22}&amp;tab=DEMO&amp;lang=PHP](https://api.aliyun.com/new?spm=a2c4g.11186623.2.13.2fc27861OpQnPn#/?product=Dypnsapi&amp;version=2017-05-25&amp;api=GetMobile&amp;params=%7B%22RegionId%22:%22cn-hangzhou%22%7D&amp;tab=DEMO&amp;lang=PHP) 这个url里面的version是填 2017-05-25，我也是填这个，结果就报错了。 想问下version参数应该怎么填 支持版本是：2017-05-25 5.6 支持 Composer 安装，如果无法使用 Composer 安装，请下载引入：https://github.com/aliyun/openapi-sdk-php/blob/master/docs/zh-CN/1-Installation.md — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你的项目的 guzzlehttp 是PHP7+的要求？阿里云SDK没有这个要求，建议检查一下依赖。

**Comment by 111Quentin** [comment]
就是使用composer把阿里云sdk包下载下来之后，根据阿里云官方调用一键取号接口的调用是用到里面的guzzlehttp包去请求的，而它的包是php7+的语法。所以我就只能追源码去封装请求这个接口的方法。 结果就是报了version参数不合法。不知道你这边能不能给下这个接口的api文档。不行我明天只能再去看下源码哪里有遗漏的请求条件




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "宋神宗"<notifications@github.com&gt;; 
发送时间: 2020年7月26日(星期天) 晚上7:45
收件人: "aliyun/openapi-sdk-php"<openapi-sdk-php@noreply.github.com&gt;; 
抄送: "1551881447"<1551881447@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [aliyun/openapi-sdk-php] 阿里云一键取号API报 Specified parameter Version is not valid (#175)





  
就是composer方式可以安装，但是由于里面使用guzzlehttp方式请求接口，guzzlehttp类库是用php7+的语法，导致我这边无法用你们推荐的方式去请求一键取号接口。所以我这边只能去追源码看一键取号接口是怎么请求的，我把参数还有参数的加密都自己封装了一遍去请求，结果报version参数不合法，我version填的是2017-05-25，是没问题的。 但是我使用php7以上版本，用你们推荐的rpc去请求接口就能正常拿到手机号，这里填的version参数也是2017-05-25
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "宋神宗"<notifications@github.com&gt;; 发送时间: 2020年7月25日(星期六) 晚上6:08 收件人: "aliyun/openapi-sdk-php"<openapi-sdk-php@noreply.github.com&gt;; 抄送: "1551881447"<1551881447@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [aliyun/openapi-sdk-php] 阿里云一键取号API报 Specified parameter Version is not valid (#175) 我这边因为项目是php5.6,不能用composer方式引入项目，所以只能去研究阿里云一键取号Api的接口参数去请求， 结果其他请求参数都没有问题，参数Version就报错，https://api.aliyun.com/new?spm=a2c4g.11186623.2.13.2fc27861OpQnPn#/?product=Dypnsapi&amp;version=2017-05-25&amp;api=GetMobile&amp;params={%22RegionId%22:%22cn-hangzhou%22}&amp;tab=DEMO&amp;lang=PHP 这个url里面的version是填 2017-05-25，我也是填这个，结果就报错了。 想问下version参数应该怎么填 支持版本是：2017-05-25 5.6 支持 Composer 安装，如果无法使用 Composer 安装，请下载引入：https://github.com/aliyun/openapi-sdk-php/blob/master/docs/zh-CN/1-Installation.md — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你的项目的 guzzlehttp 是PHP7+的要求？阿里云SDK没有这个要求，建议检查一下依赖。

**Comment by 111Quentin** [comment]
搞定了，谢谢

**Comment by songshenzong** [comment]
> 搞定了，谢谢

好的，我们强烈建议使用 Composer 管理器安装，这样会根据你的环境安装最适合你的版本，如果你只是下载引入，那会要求使用较新的版本。
