### ISSUE TITLE
带空字符串参数的请求会出现签名错误

### ISSUE THREAD

**Issue by ghostoy** [aliyun/openapi-sdk-php#177]
* **PHP 版本**：7.1-7.4
* **平台**：Linux
* **产品名称**：Vod视频点播
* **产品版本**：1.8.413
* **API**：任何API

```php
$query = [
  'Title' => 'Title',
  'Description' => '', // 只要是空的就会报签名错误
  'FileName' => 'test.mp4',
];
$request = Vod::v20170321()->createUploadVideo([
  'query' => $query,
])->endpoint($endpoint)
  ->request();
```

当手动降级alibabacloud/client版本到[1.5.24后问题才能修复](https://github.com/aliyun/openapi-sdk-php-client/issues/224)。

**Comment by songshenzong** [comment]
> * **PHP 版本**：7.1-7.4
> * **平台**：Linux
> * **产品名称**：Vod视频点播
> * **产品版本**：1.8.413
> * **API**：任何API
> 
> ```
> $query = [
>   'Title' => 'Title',
>   'Description' => '', // 只要是空的就会报签名错误
>   'FileName' => 'test.mp4',
> ];
> $request = Vod::v20170321()->createUploadVideo([
>   'query' => $query,
> ])->endpoint($endpoint)
>   ->request();
> ```
> 
> 当手动降级alibabacloud/client版本到[1.5.24后问题才能修复](https://github.com/aliyun/openapi-sdk-php-client/issues/224)。

已收到，请稍后。

**Comment by ghostoy** [comment]
client升级到1.5.29后问题修复
