### ISSUE TITLE
 内容安全图片审核报错,不知道具体原因

### ISSUE THREAD

**Issue by chenjun-0127** [aliyun/openapi-sdk-php#178]
May not yet support product Green quick access, you can use [Alibaba Cloud Client for PHP] to send any custom requests: https://github.com/aliyun/openapi-sdk-php-client/blob/master/docs/en-US/3-Request.md

**Comment by songshenzong** [comment]
> https://github.com/aliyun/openapi-sdk-php-client/blob/master/docs/en-US/3-Request.md

请按照文档指引，使用公共请求：https://github.com/aliyun/openapi-sdk-php-client/blob/master/docs/zh-CN/3-Request.md
