### ISSUE TITLE
请勿能否支持分包

### ISSUE THREAD

**Issue by shh12580** [aliyun/openapi-sdk-php#180]
不分包有太多坑，加载一个组件时，结果需要拉取左右组件，发布线上要发布好几千个文件，composer静态加载文件特别大

**Comment by songshenzong** [comment]
> 不分包有太多坑，加载一个组件时，结果需要拉取左右组件，发布线上要发布好几千个文件，composer静态加载文件特别大

您好，SDK支持按产品安装：https://github.com/aliyun/openapi-sdk-php/blob/master/SUPPORTED.md

**Comment by shh12580** [comment]
感谢
