### ISSUE TITLE
内容安全 自定义文本库使用方式？

### ISSUE THREAD

**Issue by hedeqiang** [aliyun/openapi-sdk-php#182]
* **PHP Version**:  PHP 7.3.21-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Aug  7 2020 14:44:10) ( NTS )
* **Platform**:   Linux d0aa2e73b694 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* **Product**: Green
* **Product Version**:  20180509
* **API**: getSimilarityLibrary  addSimilarityLibrary

您好，我想问下，内容安全 SDK ，创建自定义文本库。是否是 getSimilarityLibrary() 方法。我通过此方法返回状态码 200 ， 但是云盾控制台似乎没有？还是说，通过接口创建的文本库在控制台看不到？

另外，我通过 getSimilarityLibrary 获取报错。
```
$body = [
            'ServiceModule' => 'open_api'
        ];
$body = json_encode($body);
return \AlibabaCloud\Green\Green::v20180509()->getSimilarityLibrary()->body($body)->request()->toArray();
```

![image](https://user-images.githubusercontent.com/31909061/92344720-d3410c80-f0f9-11ea-8e5a-d0ef0c4d89d2.png)

**Comment by hedeqiang** [comment]
另外 如下代码 二次调用请求 返回 image library

```php
$body = [
            'ServiceModule' => 'open_api',
            'Name' => 'test',
            'ResourceType' => 'TEXT',
            'Category' => 'BLACK',
            'LibType' => 'textKeyword',
];
$body = json_encode($body);
return \AlibabaCloud\Green\Green::v20180509()->addSimilarityLibrary()->body($body)->request()->toArray();
```
![image](https://user-images.githubusercontent.com/31909061/92345269-544cd380-f0fb-11ea-8fc2-02917c5540f6.png)

**Comment by hedeqiang** [comment]
是不是我的姿势不对，好想没有添加文本的方式 https://help.aliyun.com/document_detail/106534.html?spm=a2c4g.11186623.6.709.32f51886N7ebKR

**Comment by songshenzong** [comment]
> * **PHP Version**:  PHP 7.3.21-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Aug  7 2020 14:44:10) ( NTS )
> * **Platform**:   Linux d0aa2e73b694 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> * **Product**: Green
> * **Product Version**:  20180509
> * **API**: getSimilarityLibrary  addSimilarityLibrary
> 
> 您好，我想问下，内容安全 SDK ，创建自定义文本库。是否是 getSimilarityLibrary() 方法。我通过此方法返回状态码 200 ， 但是云盾控制台似乎没有？还是说，通过接口创建的文本库在控制台看不到？
> 
> 另外，我通过 getSimilarityLibrary 获取报错。
> 
> ```
> $body = [
>             'ServiceModule' => 'open_api'
>         ];
> $body = json_encode($body);
> return \AlibabaCloud\Green\Green::v20180509()->getSimilarityLibrary()->body($body)->request()->toArray();
> ```
> 
> ![image](https://user-images.githubusercontent.com/31909061/92344720-d3410c80-f0f9-11ea-8e5a-d0ef0c4d89d2.png)

这时报错，参数不符合要求。

**Comment by songshenzong** [comment]
> 另外 如下代码 二次调用请求 返回 image library
> 
> ```
> $body = [
>             'ServiceModule' => 'open_api',
>             'Name' => 'test',
>             'ResourceType' => 'TEXT',
>             'Category' => 'BLACK',
>             'LibType' => 'textKeyword',
> ];
> $body = json_encode($body);
> return \AlibabaCloud\Green\Green::v20180509()->addSimilarityLibrary()->body($body)->request()->toArray();
> ```
> 
> ![image](https://user-images.githubusercontent.com/31909061/92345269-544cd380-f0fb-11ea-8fc2-02917c5540f6.png)

name 重复了

**Comment by hedeqiang** [comment]
其实想确定下 v20180509() 接口 关于自定义文本库的都是那几个接口，

**Comment by songshenzong** [comment]
> 其实想确定下 v20180509() 接口 关于自定义文本库的都是那几个接口，

我们的SDK都是自动生成的，如果想确定用途，建议查阅产品文档找到对应的API，再进行调用，如果查阅不清晰，可提交工单。
