### ISSUE TITLE
文档要求php版本>5.6，但实际composer安装后，需要php>7.2

### ISSUE THREAD

**Issue by lawyerlaoyang** [aliyun/openapi-sdk-php#185]
文档要求php版本>5.6，但实际composer安装后，需要php>7.2
其中依赖的组件明确要求php版本>7.2，可能是组件pcr，因此建议：
1、明确组件版本，尽量降低组件对新版的要求；
2、精确本产品安装后的实际版本需求。

* **PHP Version**:php.5.6.38
* **Platform**:macos
* **Product**: alibabacloud/sdk(sts)
* **Product Version**:最新版本
* **API**:

**Comment by AxiosCros** [comment]
这个sdk是支持php5.6的，请问您是通过何种渠道获取的sdk的？

如果是通过拷贝的方式安装，请确认打包的sdk文件，是在php5.6环境下安装的。

**Comment by AxiosCros** [comment]
我先关闭这个 issue 了，如还有疑问可重新开启。
