### ISSUE TITLE
IoT北京企业版实例调用永远不成功

### ISSUE THREAD

**Issue by everalan** [aliyun/openapi-sdk-php#187]
因为 SDK 里 endpoint 用的是公共实例的 iot.aliyun.com，实际上应该是 iot.cn-beijing.aliyun.com

**Comment by AxiosCros** [comment]
`iot.cn-beijing.aliyun.com` 是没有这个域名的 DNS 解析的。
你可以 ping 一下，会有如下报错:
```bash
ping: cannot resolve iot.cn-beijing.aliyun.com: Unknown host
```

**Comment by everalan** [comment]
抱歉写错了，应该是 Iot.cn-beijing.aliyuncs.com
删掉 endpoints.json 里的 endpoint_map.cn-beijing，或者改成 Iot.cn-beijing.aliyuncs.com 都可以。

**Comment by everalan** [comment]
请问你通过openapi测试过北京企业版吗？通过你们的调试工具都会报错。
<img width="803" alt="WX20210331-113629@2x" src="https://user-images.githubusercontent.com/3772707/113087048-6916c300-9215-11eb-835a-66a7edf44d2d.png">

**Comment by AxiosCros** [comment]
这个报错提示是产品服务接口限制您的访问频率了，和 SDK 没有关系的。您可以提工单咨询。

另外，欢迎使用我们的诊断系统进行问题诊断
https://next.api.aliyun.com/troubleshoot

**Comment by AxiosCros** [comment]
如没有其他问题，您可以关闭这个 issue
