### ISSUE TITLE
 文档写的真垃圾, 只能自己去调api了

### ISSUE THREAD

**Issue by LeeDF** [aliyun/openapi-sdk-php#193]
* **PHP 版本**：
* **平台**：
* **产品名称**：
* **产品版本**：
* **API**：

**Comment by songshenzong** [comment]
> * **PHP 版本**：
> * **平台**：
> * **产品名称**：
> * **产品版本**：
> * **API**：

请问是本项目的 README 文档还是官网产品文档？
