### ISSUE TITLE
希望能够兼容php8

### ISSUE THREAD

**Issue by lizcao** [aliyun/openapi-sdk-php#203]
**您的功能请求是否与问题有关？ 请描述一下。**
升级到php8后，安装sdk包失败。
`  Problem 1
    - ralouphie/mimey 2.1.0 requires php ^5.4|^7.0 -> your php version (8.0.11) does not satisfy that requirement.
    - alibabacloud/alimt-20181012 1.0.1 requires alibabacloud/tea-oss-utils ^0.2.0 -> satisfiable by alibabacloud/tea-oss-utils[0.2.2].
    - alibabacloud/tea-oss-utils 0.2.2 requires ralouphie/mimey ^2.1 -> satisfiable by ralouphie/mimey[2.1.0].
    - alibabacloud/alimt-20181012 is locked to version 1.0.1 and an update of this package was not requested.
`
**描述你想要的解决方案**
发现有个依赖包目前不支持php8

**描述您考虑过的替代方案**
希望能够兼容php8

**Comment by yndu13** [comment]
已兼容，https://github.com/aliyun/openapi-sdk-php-client/pull/257
