### ISSUE TITLE
不支持php8.1

### ISSUE THREAD

**Issue by bkkkd** [aliyun/openapi-sdk-php#212]
During inheritance of Countable: Uncaught think\exception\ErrorException: Return type of AlibabaCloud\Client\Result\Result::count($key = null) should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in

During inheritance of ArrayAccess: Uncaught think\exception\ErrorException: Return type of Adbar\Dot::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/vendor/adbario/php-dot-notation/src/Dot.php:510

主要是php8.1变成强类型.新多接口的类型都要强制输入输出

**Comment by aliliin** [comment]
是的呢，8.1 各种警告。
<img width="1629" alt="WX20220815-141345@2x" src="https://user-images.githubusercontent.com/22074839/184585520-302146df-c3d1-4cfa-8df7-aaa648aebbfa.png">

**Comment by williamqian** [comment]
哎，决定以后这种请求api的还是自己封装了，用他的包，不知道要等到何年何月兼容

**Comment by yndu13** [comment]
已完成兼容。
