### ISSUE TITLE
Image search empty codes

### ISSUE THREAD

**Issue by rfpdl** [aliyun/openapi-sdk-php#27]
I am currently testing Image search from this repo, but unfortunately, I am sending an empty request as per stated by the Support Engineer when doing tickets in the console. I am writing here as it was suggested by the Support engineer to raise an issue here instead.

My question is that, why is the Image search codes are empty compare to the [Aliyun open api sdk](https://github.com/aliyun/aliyun-openapi-php-sdk/tree/master/aliyun-php-sdk-imagesearch) or the [downloadable library](https://www.alibabacloud.com/help/doc-detail/71240.htm?spm=a2c63.p38356.b99.44.28f7c11er2tz3Z)

Any way you can update the image search? As I really prefer to use composer when installing libraries.

If you have a question about Alibaba Cloud that is not a bug report or feature
request, please post it in https://selfservice.console.aliyun.com/ticket/createIndex

Questions posted to this repository will be closed.

**Comment by songshenzong** [comment]
> I am currently testing Image search from this repo, but unfortunately, I am sending an empty request as per stated by the Support Engineer when doing tickets in the console. I am writing here as it was suggested by the Support engineer to raise an issue here instead.
> 
> My question is that, why is the Image search codes are empty compare to the [Aliyun open api sdk](https://github.com/aliyun/aliyun-openapi-php-sdk/tree/master/aliyun-php-sdk-imagesearch) or the [downloadable library](https://www.alibabacloud.com/help/doc-detail/71240.htm?spm=a2c63.p38356.b99.44.28f7c11er2tz3Z)
> 
> Any way you can update the image search? As I really prefer to use composer when installing libraries.
> 
> If you have a question about Alibaba Cloud that is not a bug report or feature
> request, please post it in https://selfservice.console.aliyun.com/ticket/createIndex
> 
> Questions posted to this repository will be closed.

Hello! Please visit: https://github.com/aliyun/openapi-sdk-php, you can install it using composer.
Usage:
`AlibabaCloud:: imageSearch()->xxxxx`

**Comment by rfpdl** [comment]
@songshenzong I have used the said library and install it using composer. When sending request, the body is empty(as per the support engineer).

Please check the link here: It does not have the code to set image, or set category unlink in the downloadable library.

[open sdk add item](https://github.com/aliyun/openapi-sdk-php/blob/master/src/ImageSearch/V20180120/AddItem.php)

There is no specific code in it that is used for attaching data and image to the body

**Comment by songshenzong** [comment]
Hello, we will update the code, but you can customize parameters to send requests at any time. Address: https://github.com/aliyun/openapi-sdk-php-client#request

**Comment by rfpdl** [comment]
@songshenzong May I know when will you do the update for image search? 

This is the code I am using, based on the support engineer statement, the request body is empty. 

![image](https://user-images.githubusercontent.com/46474383/52412938-9ebe3680-2af9-11e9-92f8-1023ff6fc966.png)

Thank you.

**Comment by songshenzong** [comment]
> @songshenzong May I know when will you do the update for image search?
> 
> This is the code I am using, based on the support engineer statement, the request body is empty.
> 
> ![image](https://user-images.githubusercontent.com/46474383/52412938-9ebe3680-2af9-11e9-92f8-1023ff6fc966.png)
> 
> Thank you.

Hello, we still recommend that you view https://github.com/aliyun/openapi-sdk-php-client#request. You can set any parameters through Guzzle Request Options.

![image](https://user-images.githubusercontent.com/17404625/52423863-e5c91d80-2b33-11e9-9ec4-32048d45d849.png)

**Comment by rfpdl** [comment]
I have added the sdk php client using request and removed the sdk php installed via composer.

@songshenzong Any chance you have better documentation? Especially for cust_content? Or can you please give me a sample code how to add 2 images for a product? The screenshot above does not explain what is cust_content as it is not well explained in the documentation (refer below)

The instruction in [alibaba image search instruction](https://www.alibabacloud.com/help/doc-detail/66629.htm?spm=a2c63.p38356.a3.2.532c602d4sgAAA) is really hard to understand.

questions from that link:
- what is crop?
- what is effective region?
- what is region? 
- what is the use of region? 
- the body for cust_content is really not clear with the delimiter?
- what is key 1? what do we use this for?
- what is value 1? what do we use this for?

I really need to get a sample of this service running, and really thankful if you can answer my inquiry.

**Comment by rfpdl** [comment]
@songshenzong bump

**Comment by songshenzong** [comment]
> @songshenzong bump

Processing, please wait a moment.

**Comment by songshenzong** [comment]
> @songshenzong bump

May I have your email？

**Comment by songshenzong** [comment]
> @songshenzong bump

Hello, this is not an issue with SDK but the use of the product, please provide your email address and we will arrange the relevant personnel to contact you. Or please submit a work order: https://selfservice.console.aliyun.com/ticket/createIndex

**Comment by songshenzong** [comment]
> @songshenzong bump

We released V1.0.6 which supports image search. Please update the SDK with `composer update`. For the usage, please refer to the function test code: https://github.com/aliyun/openapi-sdk-php/blob/master/tests/ Feature/ImageSearchTest.php

**Comment by songshenzong** [comment]
> @songshenzong bump

Hello, Can you use it now?

**Comment by rfpdl** [comment]
Sorry for the delay, I am still working on it. I will keep you updated once I am done with the development and testing. Just need to come up with a simple prototype. 

Thank you for the prompt update. Really appreciate it.

**Comment by rfpdl** [comment]
@songshenzong May I ask how about multiple images per item in a request?

Also, when uploading some photos. I am getting this error: 

UnsupportedPicPixels

What does this mean? What is the min size and what are the acceptable format?

**Comment by songshenzong** [comment]
> @songshenzong It is working. Really good! Thank you.
> 
> May I ask how about multiple images per item in a request?
> 
> Also, when uploading some photos. I am getting this error:
> 
> UnsupportedPicPixels
> 
> What does this mean? What is the min size and what are the acceptable format?

1. We strongly recommend that you only upload one image at a time, and you will only be able to add one image to a single request in the future.
2. `UnsupportedPicPixels` means that the size of the image does not meet the requirements of the interface.
3. The file size of each image must be at least 2 MB. Both the height and width must fall into the range from 200 pixels to 1024 pixels.
4. For more restrictions and instructions on the interface, please refer to: https://www.alibabacloud.com/help/doc-detail/74408.htm?spm=a2c63.p38356.b99.22.59253b8eUnhRAM

**Comment by songshenzong** [comment]
> > @songshenzong It is working. Really good! Thank you.
> > May I ask how about multiple images per item in a request?
> > Also, when uploading some photos. I am getting this error:
> > UnsupportedPicPixels
> > What does this mean? What is the min size and what are the acceptable format?
> 
> 1. We strongly recommend that you only upload one image at a time, and you will only be able to add one image to a single request in the future.
> 2. `UnsupportedPicPixels` means that the size of the image does not meet the requirements of the interface.
> 3. The file size of each image must be at least 2 MB. Both the height and width must fall into the range from 200 pixels to 1024 pixels.
> 4. For more restrictions and instructions on the interface, please refer to: https://www.alibabacloud.com/help/doc-detail/74408.htm?spm=a2c63.p38356.b99.22.59253b8eUnhRAM

Hello, can you use it now? Can you tell us the name of your company?

**Comment by rfpdl** [comment]
@songshenzong Yes I can use it now.

Dropped you an email.

Thank you.

**Comment by songshenzong** [comment]
> @songshenzong Yes I can use it now.
> 
> Dropped you an email.
> 
> Thank you.

You are welcome, I'll close this issue.
