### ISSUE TITLE
vod中ListVodTemplate的TemplateType参数有哪些选项？

### ISSUE THREAD

**Issue by laofu110** [aliyun/openapi-sdk-php#32]
ListVodTemplate这个接口在新版的aliyun-php-sdk-vod/vod中是ListTranscodeTemplateGroupRequest负责的（我只是从单词意思上分析的），官方文档里也没有ListVodTemplate的介绍，现在都是composer直接安装的，为啥两边不保持一致呢？

**Comment by songshenzong** [comment]
> ListVodTemplate这个接口在新版的aliyun-php-sdk-vod/vod中是ListTranscodeTemplateGroupRequest负责的（我只是从单词意思上分析的），官方文档里也没有ListVodTemplate的介绍，现在都是composer直接安装的，为啥两边不保持一致呢？

您好，我们刚刚发布了包含该接口的 V1.0.7 版本，请运行 `composer update` 升级。
https://github.com/aliyun/openapi-sdk-php 是支持composer的新版sdk，推荐使用
https://github.com/aliyun/aliyun-openapi-php-sdk 是不支持composer的旧版sdk

**Comment by laofu110** [comment]
速度可以啊，感谢感谢！还有个使用场景问题请教下，我的视频分为管理员上传与前台用户上传，考虑到转码费用的问题，管理员上传的视频可信，所以直接转码，前台用户上传的视频必须人工审核通过后由管理员手动提交转码。我们在选择视频列表的时候需要查询到列表中每个视频是否转码已经转码状态。虽然可以通过回调记录解决此问题，但是阿里云为啥不在SearchMedia的结果中显示这个状态呢，结果中的Status不管有没有转码都是Normal，这不科学啊

**Comment by songshenzong** [comment]
> 速度可以啊，感谢感谢！还有个使用场景问题请教下，我的视频分为管理员上传与前台用户上传，考虑到转码费用的问题，管理员上传的视频可信，所以直接转码，前台用户上传的视频必须人工审核通过后由管理员手动提交转码。我们在选择视频列表的时候需要查询到列表中每个视频是否转码已经转码状态。虽然可以通过回调记录解决此问题，但是阿里云为啥不在SearchMedia的结果中显示这个状态呢，结果中的Status不管有没有转码都是Normal，这不科学啊

如果您对阿里云 SDK 的问题不是 Bug 或希望添加新功能，
请在我们的工单系统提出工单：https://selfservice.console.aliyun.com/ticket/createIndex

此类问题将被关闭。

**Comment by songshenzong** [comment]
> 速度可以啊，感谢感谢！还有个使用场景问题请教下，我的视频分为管理员上传与前台用户上传，考虑到转码费用的问题，管理员上传的视频可信，所以直接转码，前台用户上传的视频必须人工审核通过后由管理员手动提交转码。我们在选择视频列表的时候需要查询到列表中每个视频是否转码已经转码状态。虽然可以通过回调记录解决此问题，但是阿里云为啥不在SearchMedia的结果中显示这个状态呢，结果中的Status不管有没有转码都是Normal，这不科学啊

请问您的公司叫什么名字？我们记录一下。
