### ISSUE TITLE
5000 多个文件 近30M 都是一些 重复性的代码. 建议减少文件量, 做点优化吧. 

### ISSUE THREAD

**Issue by xiongxinag** [aliyun/openapi-sdk-php#36]
一般使用 阿里云的 sdk 都是使用一小部分. 这个包大且全. 但是里面很多重复的东西是可以提出来重构优化的. 能大大减少文件量和使用成本.

**Comment by songshenzong** [comment]
> 一般使用 阿里云的 sdk 都是使用一小部分. 这个包大且全. 但是里面很多重复的东西是可以提出来重构优化的. 能大大减少文件量和使用成本.

感谢建议，我们会在下一代做出优化。
