### ISSUE TITLE
mnsClient BatchReceiveMessage 参数bug

### ISSUE THREAD

**Issue by chinayin** [aliyun/openapi-sdk-php#79]
* **PHP Version**:7.2
* **Platform**:mac
* **Product**:mns
* **Product Version**:1.2.4
* **API**: BatchReceiveMessage

hi  
sdk中提供的mnsClient存在参数问题  导致无法正常获取mns队列消息

我方在升级使用新版php-sdk, 出现无法拉取mns消息bug
阿里云官方工单反馈如下
工程师 60810 号 :    您好，已经为您核实，您的这个sdk不是消息服务mns官方提供的sdk，传的参数WaitSeconds 这个是非标准的，标准的应该是：waitseconds，还要请您知晓哈，官方提供的mns的sdk，您可以参考下
https://help.aliyun.com/document_detail/32381.html?spm=a2c4g.11186623.6.655.2b947f87MOpJpF
您使用这个sdk测试下，看是否还有500的情况呢？  

经查证问题出自 
AlibabaCloud\Dybaseapi\MNS\Requests\BatchReceiveMessage;
line:86 88 两个参数错误

请核实.

**Comment by chinayin** [comment]
我在升级公司项目时,对照官方mnsapi在openapi-sdk-php做了相关适配.
想问下是否有融合mns相关api的计划? 如无,我就自己把mns的request都补全了

**Comment by chinayin** [comment]
补充一下  MNS官方文档中 https://help.aliyun.com/document_detail/35137.html
numOfMessages 也是写错的  应该是 NumOfMessages

**Comment by songshenzong** [comment]
> * **PHP Version**:7.2
> * **Platform**:mac
> * **Product**:mns
> * **Product Version**:1.2.4
> * **API**: BatchReceiveMessage
> 
> hi
> sdk中提供的mnsClient存在参数问题 导致无法正常获取mns队列消息
> 
> 我方在升级使用新版php-sdk, 出现无法拉取mns消息bug
> 阿里云官方工单反馈如下
> 工程师 60810 号 : 您好，已经为您核实，您的这个sdk不是消息服务mns官方提供的sdk，传的参数WaitSeconds 这个是非标准的，标准的应该是：waitseconds，还要请您知晓哈，官方提供的mns的sdk，您可以参考下
> https://help.aliyun.com/document_detail/32381.html?spm=a2c4g.11186623.6.655.2b947f87MOpJpF
> 您使用这个sdk测试下，看是否还有500的情况呢？
> 
> 经查证问题出自
> AlibabaCloud\Dybaseapi\MNS\Requests\BatchReceiveMessage;
> line:86 88 两个参数错误
> 
> 请核实.

正在联系相关产品核实，请稍等。

**Comment by songshenzong** [comment]
> 我在升级公司项目时,对照官方mnsapi在openapi-sdk-php做了相关适配.
> 想问下是否有融合mns相关api的计划? 如无,我就自己把mns的request都补全了

已经修复完毕，请升级版本 composer update 到 V1.2.9

**Comment by chinayin** [comment]
好的,感谢

**Comment by chinayin** [comment]
修复的有问题 

官方sdk中 BatchReceiveMessageRequest 
```php 
 public function generateQueryString()
    {
        $params = array("numOfMessages" => $this->numOfMessages);
        if ($this->waitSeconds != NULL)
        {
            $params["waitseconds"] = $this->waitSeconds;
        }
        return http_build_query($params);
    }
```
> numOfMessages  waitseconds

在调用时  numOfMessages 这样传递会报错 如下:
```
.MissingArgument: Required Integer parameter 'NumOfMessages' is not present RequestId: 5C9AEE57314545DD2833A136
```
1. 所以正确的是  NumOfMessages
2. 工单中客服肯定 waitseconds 参数是需要这样传  不知道内部是否有 waitSeconds的写法 这个无法通过接口报错来辨识(这个还需要请再跟后端开发确认下,因为这个会影响到我们在生产环境升级sdk后使用)

**Comment by songshenzong** [comment]
> 修复的有问题
> 
> 官方sdk中 BatchReceiveMessageRequest
> 
> ```
>  public function generateQueryString()
>     {
>         $params = array("numOfMessages" => $this->numOfMessages);
>         if ($this->waitSeconds != NULL)
>         {
>             $params["waitseconds"] = $this->waitSeconds;
>         }
>         return http_build_query($params);
>     }
> ```
> 
> > numOfMessages  waitseconds
> 
> 在调用时 numOfMessages 这样传递会报错 如下:
> 
> ```
> .MissingArgument: Required Integer parameter 'NumOfMessages' is not present RequestId: 5C9AEE57314545DD2833A136
> ```
> 1. 所以正确的是  NumOfMessages
> 2. 工单中客服肯定 waitseconds 参数是需要这样传  不知道内部是否有 waitSeconds的写法 这个无法通过接口报错来辨识(这个还需要请再跟后端开发确认下,因为这个会影响到我们在生产环境升级sdk后使用)

请稍等，可否方便提供其他的联系方式？ 邮箱，钉钉。

**Comment by songshenzong** [comment]
> 修复的有问题
> 
> 官方sdk中 BatchReceiveMessageRequest
> 
> ```
>  public function generateQueryString()
>     {
>         $params = array("numOfMessages" => $this->numOfMessages);
>         if ($this->waitSeconds != NULL)
>         {
>             $params["waitseconds"] = $this->waitSeconds;
>         }
>         return http_build_query($params);
>     }
> ```
> 
> > numOfMessages  waitseconds
> 
> 在调用时 numOfMessages 这样传递会报错 如下:
> 
> ```
> .MissingArgument: Required Integer parameter 'NumOfMessages' is not present RequestId: 5C9AEE57314545DD2833A136
> ```
> 1. 所以正确的是  NumOfMessages
> 2. 工单中客服肯定 waitseconds 参数是需要这样传  不知道内部是否有 waitSeconds的写法 这个无法通过接口报错来辨识(这个还需要请再跟后端开发确认下,因为这个会影响到我们在生产环境升级sdk后使用)

建议您在工单中和API产品同学确认

**Comment by yizhihouzi** [comment]
同样面对这个问题.提示 MissingArgument: Required Integer parameter 'NumOfMessages' is not present RequestId: 5CA8A875454131D64449B6C4   
你们处理问题都不测试的吗?这么久了还没修复好,而且issue被关闭

**Comment by songshenzong** [comment]
> 同样面对这个问题.提示 MissingArgument: Required Integer parameter 'NumOfMessages' is not present RequestId: 5CA8A875454131D64449B6C4
> 你们处理问题都不测试的吗?这么久了还没修复好,而且issue被关闭

您好，我们已经开始高优处理，请稍等。

**Comment by songshenzong** [comment]
> 同样面对这个问题.提示 MissingArgument: Required Integer parameter 'NumOfMessages' is not present RequestId: 5CA8A875454131D64449B6C4
> 你们处理问题都不测试的吗?这么久了还没修复好,而且issue被关闭

我们已经发布了 V1.3.4 解决此问题，请使用 composer update 更新到新版本。

**Comment by songshenzong** [comment]
> 修复的有问题
> 
> 官方sdk中 BatchReceiveMessageRequest
> 
> ```
>  public function generateQueryString()
>     {
>         $params = array("numOfMessages" => $this->numOfMessages);
>         if ($this->waitSeconds != NULL)
>         {
>             $params["waitseconds"] = $this->waitSeconds;
>         }
>         return http_build_query($params);
>     }
> ```
> 
> > numOfMessages  waitseconds
> 
> 在调用时 numOfMessages 这样传递会报错 如下:
> 
> ```
> .MissingArgument: Required Integer parameter 'NumOfMessages' is not present RequestId: 5C9AEE57314545DD2833A136
> ```
> 1. 所以正确的是  NumOfMessages
> 2. 工单中客服肯定 waitseconds 参数是需要这样传  不知道内部是否有 waitSeconds的写法 这个无法通过接口报错来辨识(这个还需要请再跟后端开发确认下,因为这个会影响到我们在生产环境升级sdk后使用)

我们已经发布了 V1.3.4 解决此问题，请使用 composer update 更新到新版本。
