### ISSUE TITLE
Dm Versions contains no V20151123

### ISSUE THREAD

**Issue by chinayin** [aliyun/openapi-sdk-php#86]
报错  `Dm Versions contains no V20151123`

版本 1.2.10

```php
$request = AlibabaCloud::dm()->v20151123()->singleSendMail()
            //管理控制台中配置的发信地址。
            ->withAccountName($from_mail)
            //发信人昵称,长度小于 15 个字符。 例如:发信人昵称设置为”小红”，发信地址为 “test@example.com”，收信人看到的发信地址为"小红"<test@example.com>
            ->withFromAlias($from_alias)
            //取值范围 0~1: 0 为随机账号；1 为发信地址。
            ->withAddressType($is_random_address ? 0 : 1)
            //使用管理控制台中配置的回信地址（状态必须是验证通过）。
            ->withReplyToAddress('true')
            // 目标地址，多个 email 地址可以用逗号分隔，最多100个地址。
            ->withToAddress($email)
            // 收件标题
            ->withSubject($subject)
            // 收件正文
            ->withHtmlBody($content);
```

**Comment by songshenzong** [comment]
> 报错 `Dm Versions contains no V20151123`
> 
> 版本 1.2.10
> 
> ```
> $request = AlibabaCloud::dm()->v20151123()->singleSendMail()
>             //管理控制台中配置的发信地址。
>             ->withAccountName($from_mail)
>             //发信人昵称,长度小于 15 个字符。 例如:发信人昵称设置为”小红”，发信地址为 “test@example.com”，收信人看到的发信地址为"小红"<test@example.com>
>             ->withFromAlias($from_alias)
>             //取值范围 0~1: 0 为随机账号；1 为发信地址。
>             ->withAddressType($is_random_address ? 0 : 1)
>             //使用管理控制台中配置的回信地址（状态必须是验证通过）。
>             ->withReplyToAddress('true')
>             // 目标地址，多个 email 地址可以用逗号分隔，最多100个地址。
>             ->withToAddress($email)
>             // 收件标题
>             ->withSubject($subject)
>             // 收件正文
>             ->withHtmlBody($content);
> ```

生成类映射 - 必须执行这个命令，否则可能无法使用。

composer dump-autoload --optimize
在 composer.json 中 config 部分设置 "optimize-autoloader": true 可免执行 dump-autoload --optimize。

**Comment by songshenzong** [comment]
> 报错 `Dm Versions contains no V20151123`
> 
> 版本 1.2.10
> 
> ```
> $request = AlibabaCloud::dm()->v20151123()->singleSendMail()
>             //管理控制台中配置的发信地址。
>             ->withAccountName($from_mail)
>             //发信人昵称,长度小于 15 个字符。 例如:发信人昵称设置为”小红”，发信地址为 “test@example.com”，收信人看到的发信地址为"小红"<test@example.com>
>             ->withFromAlias($from_alias)
>             //取值范围 0~1: 0 为随机账号；1 为发信地址。
>             ->withAddressType($is_random_address ? 0 : 1)
>             //使用管理控制台中配置的回信地址（状态必须是验证通过）。
>             ->withReplyToAddress('true')
>             // 目标地址，多个 email 地址可以用逗号分隔，最多100个地址。
>             ->withToAddress($email)
>             // 收件标题
>             ->withSubject($subject)
>             // 收件正文
>             ->withHtmlBody($content);
> ```

使用方法昨天已回复，如果没有其他问题，此Issue将被关闭。
